# Generated by Django 2.1.7 on 2019-02-22 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=40)),
                ('mid', models.IntegerField(unique=True)),
                ('record_time', models.DateTimeField()),
                ('keep_on', models.BooleanField()),
                ('mini_mode', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VIDEO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=40)),
                ('aid', models.IntegerField()),
                ('record_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('tracing', models.BooleanField()),
            ],
        ),
    ]
