# Generated by Django 2.1.7 on 2019-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdvs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='up',
            name='id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AlterField(
            model_name='up',
            name='mid',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='aid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
