# Generated by Django 2.1.7 on 2019-04-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdvs', '0003_auto_20190408_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='up',
            name='verify',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='up',
            name='verify_reason',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='record_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
